#pragma once

#ifdef _DEBUG
#define VIRTUAL_DESTRUCTOR_FOR_DEBUGGING virtual
#else
#define VIRTUAL_DESTRUCTOR_FOR_DEBUGGING
#endif  // DEBUG

#define VIRTUAL_DESTRUCTOR_FOR_DEBUGGING_DEFAULT(class) \
  VIRTUAL_DESTRUCTOR_FOR_DEBUGGING ~class() = default;
