var searchData=
[
  ['terms_20and_20definitions_20in_20context_20of_20any_0',['Terms and Definitions in Context of &lt;span class=&quot;tt&quot;&gt;Any++&lt;/span&gt;',['../md_docs_2terms__and__definitions.html',1,'']]],
  ['the_20generated_20code_1',['Description of the Generated Code',['../md_docs_2Traits__inner__working.html#autotoc_md25',1,'']]],
  ['the_20inner_20working_20of_20traits_20in_20any_2',['The Inner Working Of &lt;span class=&quot;tt&quot;&gt;Traits&lt;/span&gt; In &lt;span class=&quot;tt&quot;&gt;Any++&lt;/span&gt;',['../md_docs_2Traits__inner__working.html',1,'']]],
  ['the_20repo_3a_3',['Clone the repo:',['../index.html#autotoc_md30',1,'']]],
  ['to_20trait_20any_20virtual_20static_20or_20variant_4',['to trait any virtual static or variant',['../index.html#autotoc_md26',1,'Any++ : How to &lt;span class=&quot;tt&quot;&gt;trait&lt;/span&gt; &lt;span class=&quot;tt&quot;&gt;any&lt;/span&gt; &lt;span class=&quot;tt&quot;&gt;virtual&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;static&lt;/span&gt; or &lt;span class=&quot;tt&quot;&gt;variant&lt;/span&gt;?'],['../md_docs_2announcement__r__cpp.html',1,'How to &lt;tt&gt;trait&lt;/tt&gt; &lt;tt&gt;any&lt;/tt&gt; &lt;tt&gt;virtual&lt;/tt&gt;, &lt;tt&gt;static&lt;/tt&gt; or &lt;tt&gt;variant&lt;/tt&gt;?']]],
  ['trait_5',['TRAIT',['../group__trait__macros.html#gae0cb5618c6b82d8f6a7eaf36143647a9',1,'anyxx.hpp']]],
  ['trait_20and_20any_5f_20macros_6',['TRAIT... and ANY_ macros',['../group__trait__macros.html',1,'']]],
  ['trait_20any_20virtual_20static_20or_20variant_7',['trait any virtual static or variant',['../index.html#autotoc_md26',1,'Any++ : How to &lt;span class=&quot;tt&quot;&gt;trait&lt;/span&gt; &lt;span class=&quot;tt&quot;&gt;any&lt;/span&gt; &lt;span class=&quot;tt&quot;&gt;virtual&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;static&lt;/span&gt; or &lt;span class=&quot;tt&quot;&gt;variant&lt;/span&gt;?'],['../md_docs_2announcement__r__cpp.html',1,'How to &lt;tt&gt;trait&lt;/tt&gt; &lt;tt&gt;any&lt;/tt&gt; &lt;tt&gt;virtual&lt;/tt&gt;, &lt;tt&gt;static&lt;/tt&gt; or &lt;tt&gt;variant&lt;/tt&gt;?']]],
  ['trait_20jacket_8',['Trait jacket',['../md_docs_2terms__and__definitions.html#autotoc_md10',1,'']]],
  ['trait_5f_9',['TRAIT_',['../group__trait__macros.html#gadf5ede586c04f0c23d0b46a60e1d241b',1,'anyxx.hpp']]],
  ['trait_5fas_10',['trait_as',['../anyxx_8hpp.html#aa0a344700732ba661e0fb701ef1eba2c',1,'anyxx']]],
  ['trait_5fex_11',['TRAIT_EX',['../group__trait__macros.html#gae6aebc8db498e6ac66bb2d3011f91c1c',1,'anyxx.hpp']]],
  ['trait_5fex_5f_12',['TRAIT_EX_',['../group__trait__macros.html#ga15fb0b1b9a60d6586108d9bd6cec2a54',1,'anyxx.hpp']]],
  ['trait_5ftemplate_13',['TRAIT_TEMPLATE',['../group__trait__macros.html#gad2f206b96947eeba0d7f5cee72b33cae',1,'anyxx.hpp']]],
  ['trait_5ftemplate_5f_14',['TRAIT_TEMPLATE_',['../group__trait__macros.html#ga9ec9a5f2d475d1ddf481df8385fce4a1',1,'anyxx.hpp']]],
  ['trait_5ftemplate_5fex_15',['TRAIT_TEMPLATE_EX',['../group__trait__macros.html#ga8d4680fe2c2a272dcb00310f92cfbb39',1,'anyxx.hpp']]],
  ['trait_5ftemplate_5fex_5f_16',['TRAIT_TEMPLATE_EX_',['../group__trait__macros.html#ga5ee874de4f2988dc14324d0e652712aa',1,'anyxx.hpp']]],
  ['traits_20for_20c_20with_20flexible_20type_20erasure_20std_3a_3aany_20traits_20open_20dispatch_17',['Any++: Rust-like traits for C++ with flexible type erasure (std::any + traits + open dispatch)',['../md_docs_2announcement__r__cpp.html#autotoc_md1',1,'']]],
  ['traits_20in_20any_18',['The Inner Working Of &lt;span class=&quot;tt&quot;&gt;Traits&lt;/span&gt; In &lt;span class=&quot;tt&quot;&gt;Any++&lt;/span&gt;',['../md_docs_2Traits__inner__working.html',1,'']]],
  ['traits_20open_20dispatch_19',['Any++: Rust-like traits for C++ with flexible type erasure (std::any + traits + open dispatch)',['../md_docs_2announcement__r__cpp.html#autotoc_md1',1,'']]],
  ['txt_3a_20',['Useage in CMakeLists.txt:',['../index.html#autotoc_md29',1,'']]],
  ['type_20erased_20binary_20operator_21',['Showcase 3: &lt;em&gt;Any++&lt;/em&gt; Open Multi Dispatch, (Type Erased Binary Operator)',['../index.html#autotoc_md34',1,'']]],
  ['type_20erased_20proxy_20s_22',['&lt;span class=&quot;tt&quot;&gt;Any++&lt;/span&gt; Type Erased &lt;span class=&quot;tt&quot;&gt;Proxy&lt;/span&gt;*s',['../md_docs_2Proxy__overview.html',1,'']]],
  ['type_20erasure_20std_3a_3aany_20traits_20open_20dispatch_23',['Any++: Rust-like traits for C++ with flexible type erasure (std::any + traits + open dispatch)',['../md_docs_2announcement__r__cpp.html#autotoc_md1',1,'']]],
  ['typed_5fany_24',['&apos;any&apos; Versus &apos;typed_any&apos;',['../md_docs_2terms__and__definitions.html#autotoc_md17',1,'']]]
];
