var searchData=
[
  ['terms_20and_20definitions_20in_20context_20of_20this_20library_0',['Terms and Definitions in Context of This Library',['../md_docs_2terms__and__definitions.html',1,'']]],
  ['that_20erases_20the_20type_20of_20another_20object_20for_20a_20given_20lifetime_20kind_1',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['that_20struct_2',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md28',1,'']]],
  ['the_20content_20of_20an_20other_20proxy_20with_20different_20liftime_20within_20certain_20rules_3',['An &lt;b&gt;proxy&lt;/b&gt; can recieve the content of an other &lt;b&gt;proxy&lt;/b&gt; with different &lt;b&gt;liftime&lt;/b&gt; within certain rules.',['../md_docs_2terms__and__definitions.html#autotoc_md20',1,'']]],
  ['the_20definition_20of_20that_20struct_4',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md28',1,'']]],
  ['the_20eunerased_20type_5',['A &lt;em&gt;typed_any&lt;/em&gt; is a convenience wrapper of an &lt;b&gt;any&lt;/b&gt; for the &lt;b&gt;eunerased&lt;/b&gt; type.',['../md_docs_2terms__and__definitions.html#autotoc_md12',1,'']]],
  ['the_20extension_20method_20to_20solve_20the_20multiple_20dispatch_6',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['the_20first_20paramater_20must_20be_20an_20any_7',['An &lt;b&gt;extension method&lt;/b&gt; is a freestanding callable, witch acts a dispatch_table_function on the first paramater. (must be an &lt;b&gt;any&lt;/b&gt;).',['../md_docs_2terms__and__definitions.html#autotoc_md25',1,'']]],
  ['the_20multiple_20dispatch_8',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['the_20type_20of_20another_20object_20for_20a_20given_20lifetime_20kind_9',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['this_20library_10',['Terms and Definitions in Context of This Library',['../md_docs_2terms__and__definitions.html',1,'']]],
  ['three_20rules_3a_11',['Three ways, three rules:',['../md_docs_2terms__and__definitions.html#autotoc_md21',1,'']]],
  ['three_20ways_20three_20rules_3a_12',['Three ways, three rules:',['../md_docs_2terms__and__definitions.html#autotoc_md21',1,'']]],
  ['to_20a_20general_20one_13',['An &lt;em&gt;upcast&lt;/em&gt; is a &lt;em&gt;conversion&lt;/em&gt; from a more detailed type to a general one.',['../md_docs_2terms__and__definitions.html#autotoc_md17',1,'']]],
  ['to_20a_20more_20detailed_20one_14',['A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.',['../md_docs_2terms__and__definitions.html#autotoc_md18',1,'']]],
  ['to_20solve_20the_20multiple_20dispatch_15',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['to_20trait_20any_20virtual_20static_20or_20variant_16',['Any++ : How to &lt;em&gt;trait&lt;/em&gt; &lt;em&gt;any&lt;/em&gt; &lt;em&gt;virtual&lt;/em&gt;, &lt;em&gt;static&lt;/em&gt; or &lt;em&gt;variant&lt;/em&gt;?',['../index.html#autotoc_md30',1,'']]],
  ['to_20valid_20functions_17',['An object derived from v_table, with no additional members, and where all members point to valid functions.',['../md_docs_2terms__and__definitions.html#autotoc_md6',1,'']]],
  ['trait_18',['TRAIT',['../group__trait__macros.html#gae0cb5618c6b82d8f6a7eaf36143647a9',1,'anyxx.hpp']]],
  ['trait_20and_20any_5f_20macros_19',['TRAIT... and ANY_ macros',['../group__trait__macros.html',1,'']]],
  ['trait_20any_20virtual_20static_20or_20variant_20',['Any++ : How to &lt;em&gt;trait&lt;/em&gt; &lt;em&gt;any&lt;/em&gt; &lt;em&gt;virtual&lt;/em&gt;, &lt;em&gt;static&lt;/em&gt; or &lt;em&gt;variant&lt;/em&gt;?',['../index.html#autotoc_md30',1,'']]],
  ['trait_5f_21',['TRAIT_',['../group__trait__macros.html#gadf5ede586c04f0c23d0b46a60e1d241b',1,'anyxx.hpp']]],
  ['trait_5fas_22',['trait_as',['../anyxx_8hpp.html#aa0a344700732ba661e0fb701ef1eba2c',1,'anyxx']]],
  ['trait_5fex_23',['TRAIT_EX',['../group__trait__macros.html#gae6aebc8db498e6ac66bb2d3011f91c1c',1,'anyxx.hpp']]],
  ['trait_5fex_5f_24',['TRAIT_EX_',['../group__trait__macros.html#ga15fb0b1b9a60d6586108d9bd6cec2a54',1,'anyxx.hpp']]],
  ['trait_5ftemplate_25',['TRAIT_TEMPLATE',['../group__trait__macros.html#gad2f206b96947eeba0d7f5cee72b33cae',1,'anyxx.hpp']]],
  ['trait_5ftemplate_5f_26',['TRAIT_TEMPLATE_',['../group__trait__macros.html#ga9ec9a5f2d475d1ddf481df8385fce4a1',1,'anyxx.hpp']]],
  ['trait_5ftemplate_5fex_5f_27',['TRAIT_TEMPLATE_EX_',['../group__trait__macros.html#ga5ee874de4f2988dc14324d0e652712aa',1,'anyxx.hpp']]],
  ['tunnel_28',['&lt;em&gt;Ad hoc&lt;/em&gt; Type Erasure Versus Architectural &lt;em&gt;Type Tunnel&lt;/em&gt;',['../md_docs_2terms__and__definitions.html#autotoc_md29',1,'']]],
  ['txt_3a_29',['Useage in CMakeLists.txt:',['../index.html#autotoc_md33',1,'']]],
  ['type_30',['A &lt;em&gt;typed_any&lt;/em&gt; is a convenience wrapper of an &lt;b&gt;any&lt;/b&gt; for the &lt;b&gt;eunerased&lt;/b&gt; type.',['../md_docs_2terms__and__definitions.html#autotoc_md12',1,'']]],
  ['type_20erasure_20versus_20architectural_20type_20tunnel_31',['&lt;em&gt;Ad hoc&lt;/em&gt; Type Erasure Versus Architectural &lt;em&gt;Type Tunnel&lt;/em&gt;',['../md_docs_2terms__and__definitions.html#autotoc_md29',1,'']]],
  ['type_20of_20another_20object_20for_20a_20given_20lifetime_20kind_32',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['type_20to_20a_20general_20one_33',['An &lt;em&gt;upcast&lt;/em&gt; is a &lt;em&gt;conversion&lt;/em&gt; from a more detailed type to a general one.',['../md_docs_2terms__and__definitions.html#autotoc_md17',1,'']]],
  ['type_20to_20a_20more_20detailed_20one_34',['A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.',['../md_docs_2terms__and__definitions.html#autotoc_md18',1,'']]],
  ['type_20tunnel_35',['&lt;em&gt;Ad hoc&lt;/em&gt; Type Erasure Versus Architectural &lt;em&gt;Type Tunnel&lt;/em&gt;',['../md_docs_2terms__and__definitions.html#autotoc_md29',1,'']]],
  ['typed_5fany_36',['&apos;any&apos; Versus &apos;typed_any&apos;',['../md_docs_2terms__and__definitions.html#autotoc_md10',1,'']]],
  ['typed_5fany_20is_20a_20convenience_20wrapper_20of_20an_20any_20for_20the_20eunerased_20type_37',['A &lt;em&gt;typed_any&lt;/em&gt; is a convenience wrapper of an &lt;b&gt;any&lt;/b&gt; for the &lt;b&gt;eunerased&lt;/b&gt; type.',['../md_docs_2terms__and__definitions.html#autotoc_md12',1,'']]],
  ['types_38',['While &lt;em&gt;up-&lt;/em&gt; and &lt;em&gt;downcasts&lt;/em&gt; are within related types, &lt;em&gt;crosscasts&lt;/em&gt; are between unrelated types.',['../md_docs_2terms__and__definitions.html#autotoc_md23',1,'']]],
  ['types_20crosscasts_20are_20between_20unrelated_20types_39',['While &lt;em&gt;up-&lt;/em&gt; and &lt;em&gt;downcasts&lt;/em&gt; are within related types, &lt;em&gt;crosscasts&lt;/em&gt; are between unrelated types.',['../md_docs_2terms__and__definitions.html#autotoc_md23',1,'']]],
  ['types_20overview_40',['Any++ &lt;em&gt;Proxy&lt;/em&gt; types overview',['../md_docs_2erased__data__overview.html',1,'']]]
];
