var searchData=
[
  ['data_20macros_0',['Runtime data macros',['../group__runtime__macros.html',1,'']]],
  ['data_20members_20without_20changing_20the_20definition_20of_20that_20struct_1',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md30',1,'']]],
  ['define_2',['define',['../classanyxx_1_1dispatch_3_01R_07Args_8_8_8_08_4.html#a1780e02d465d06adc100e5ebdc451049',1,'anyxx::dispatch&lt; R(Args...)&gt;']]],
  ['definition_20of_20that_20struct_3',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md30',1,'']]],
  ['definitions_20in_20context_20of_20this_20library_4',['Terms and Definitions in Context of This Library',['../md_docs_2terms__and__definitions.html',1,'']]],
  ['derived_20from_20v_5ftable_20with_20no_20additional_20members_20and_20where_20all_20members_20point_20to_20valid_20functions_5',['An object derived from v_table, with no additional members, and where all members point to valid functions.',['../md_docs_2terms__and__definitions.html#autotoc_md8',1,'']]],
  ['describing_20an_20object_20that_20erases_20the_20type_20of_20another_20object_20for_20a_20given_20lifetime_20kind_6',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md11',1,'']]],
  ['description_20of_20the_20generated_20code_7',['Description of the Generated Code',['../md_docs_2architectural__overview.html#autotoc_md2',1,'']]],
  ['detailed_20one_8',['A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.',['../md_docs_2terms__and__definitions.html#autotoc_md20',1,'']]],
  ['detailed_20type_20to_20a_20general_20one_9',['An &lt;em&gt;upcast&lt;/em&gt; is a &lt;em&gt;conversion&lt;/em&gt; from a more detailed type to a general one.',['../md_docs_2terms__and__definitions.html#autotoc_md19',1,'']]],
  ['different_20liftime_20within_20certain_20rules_10',['An &lt;b&gt;proxy&lt;/b&gt; can recieve the content of an other &lt;b&gt;proxy&lt;/b&gt; with different &lt;b&gt;liftime&lt;/b&gt; within certain rules.',['../md_docs_2terms__and__definitions.html#autotoc_md22',1,'']]],
  ['dispatch_11',['dispatch',['../md_docs_2terms__and__definitions.html#autotoc_md28',1,'A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .'],['../classanyxx_1_1dispatch.html',1,'anyxx::dispatch&lt; R, Args &gt;']]],
  ['dispatch_20matrix_12',['dispatch_table, dispatch_table instance, multi dispatch matrix',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['dispatch_3c_20r_28args_2e_2e_2e_29_3e_13',['dispatch&lt; R(Args...)&gt;',['../classanyxx_1_1dispatch_3_01R_07Args_8_8_8_08_4.html',1,'anyxx']]],
  ['dispatch_5ftable_20dispatch_5ftable_20instance_20multi_20dispatch_20matrix_14',['dispatch_table, dispatch_table instance, multi dispatch matrix',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['dispatch_5ftable_20instance_20multi_20dispatch_20matrix_15',['dispatch_table, dispatch_table instance, multi dispatch matrix',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['dispatch_5ftable_5ffunction_20on_20the_20first_20paramater_20must_20be_20an_20any_16',['An &lt;b&gt;extension method&lt;/b&gt; is a freestanding callable, witch acts a dispatch_table_function on the first paramater. (must be an &lt;b&gt;any&lt;/b&gt;).',['../md_docs_2terms__and__definitions.html#autotoc_md27',1,'']]],
  ['dispatchs_5fcount_17',['dispatchs_count',['../anyxx_8hpp.html#ad0e4d3c5ff9f0082cf07ef367b55c87a',1,'anyxx']]],
  ['downcast_18',['&apos;Upcast&apos; vs &apos;Downcast&apos;',['../md_docs_2terms__and__definitions.html#autotoc_md18',1,'']]],
  ['downcast_20is_20a_20conversion_20from_20a_20more_20general_20type_20to_20a_20more_20detailed_20one_19',['A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.',['../md_docs_2terms__and__definitions.html#autotoc_md20',1,'']]],
  ['downcast_5fto_20',['downcast_to',['../group__casts.html#gadd0bed70326711f39e2efc190d006590',1,'anyxx']]],
  ['downcasts_20are_20within_20related_20types_20crosscasts_20are_20between_20unrelated_20types_21',['While &lt;em&gt;up-&lt;/em&gt; and &lt;em&gt;downcasts&lt;/em&gt; are within related types, &lt;em&gt;crosscasts&lt;/em&gt; are between unrelated types.',['../md_docs_2terms__and__definitions.html#autotoc_md25',1,'']]],
  ['dynamic_20cast_22',['Static Cast vs Dynamic Cast',['../md_docs_2terms__and__definitions.html#autotoc_md15',1,'']]],
  ['dynamic_20cast_3a_23',['A &lt;em&gt;dynamic cast&lt;/em&gt;:',['../md_docs_2terms__and__definitions.html#autotoc_md17',1,'']]]
];
