var searchData=
[
  ['object_20derived_20from_20v_5ftable_20with_20no_20additional_20members_20and_20where_20all_20members_20point_20to_20valid_20functions_0',['An object derived from v_table, with no additional members, and where all members point to valid functions.',['../md_docs_2terms__and__definitions.html#autotoc_md6',1,'']]],
  ['object_20for_20a_20given_20lifetime_20kind_1',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['object_20that_20erases_20the_20type_20of_20another_20object_20for_20a_20given_20lifetime_20kind_2',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['of_20an_20any_20for_20the_20eunerased_20type_3',['A &lt;em&gt;typed_any&lt;/em&gt; is a convenience wrapper of an &lt;b&gt;any&lt;/b&gt; for the &lt;b&gt;eunerased&lt;/b&gt; type.',['../md_docs_2terms__and__definitions.html#autotoc_md12',1,'']]],
  ['of_20an_20other_20proxy_20with_20different_20liftime_20within_20certain_20rules_4',['An &lt;b&gt;proxy&lt;/b&gt; can recieve the content of an other &lt;b&gt;proxy&lt;/b&gt; with different &lt;b&gt;liftime&lt;/b&gt; within certain rules.',['../md_docs_2terms__and__definitions.html#autotoc_md20',1,'']]],
  ['of_20another_20object_20for_20a_20given_20lifetime_20kind_5',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md9',1,'']]],
  ['of_20erased_20functionality_20in_20virtual_5fvoid_6',['Comparison of &lt;em&gt;erased functionality&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;virtual_void&lt;/span&gt;',['../md_docs_2erased__functionality.html',1,'']]],
  ['of_20that_20struct_7',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md28',1,'']]],
  ['of_20the_20extension_20method_20to_20solve_20the_20multiple_20dispatch_8',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['of_20this_20library_9',['Terms and Definitions in Context of This Library',['../md_docs_2terms__and__definitions.html',1,'']]],
  ['on_20the_20first_20paramater_20must_20be_20an_20any_10',['An &lt;b&gt;extension method&lt;/b&gt; is a freestanding callable, witch acts a dispatch_table_function on the first paramater. (must be an &lt;b&gt;any&lt;/b&gt;).',['../md_docs_2terms__and__definitions.html#autotoc_md25',1,'']]],
  ['one_11',['one',['../md_docs_2terms__and__definitions.html#autotoc_md18',1,'A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.'],['../md_docs_2terms__and__definitions.html#autotoc_md17',1,'An &lt;em&gt;upcast&lt;/em&gt; is a &lt;em&gt;conversion&lt;/em&gt; from a more detailed type to a general one.']]],
  ['operator_28_29_12',['operator()',['../classanyxx_1_1dispatch_3_01R_07Args_8_8_8_08_4.html#a7e8628df49b55d4cfa4ef8c8c5adae2c',1,'anyxx::dispatch&lt; R(Args...)&gt;']]],
  ['or_20variant_13',['Any++ : How to &lt;em&gt;trait&lt;/em&gt; &lt;em&gt;any&lt;/em&gt; &lt;em&gt;virtual&lt;/em&gt;, &lt;em&gt;static&lt;/em&gt; or &lt;em&gt;variant&lt;/em&gt;?',['../index.html#autotoc_md30',1,'']]],
  ['other_20proxy_20with_20different_20liftime_20within_20certain_20rules_14',['An &lt;b&gt;proxy&lt;/b&gt; can recieve the content of an other &lt;b&gt;proxy&lt;/b&gt; with different &lt;b&gt;liftime&lt;/b&gt; within certain rules.',['../md_docs_2terms__and__definitions.html#autotoc_md20',1,'']]],
  ['overview_15',['overview',['../md_docs_2erased__data__overview.html',1,'Any++ &lt;em&gt;Proxy&lt;/em&gt; types overview'],['../md_docs_2architectural__overview.html',1,'Architectural overview']]]
];
