var searchData=
[
  ['erased_20functionality_20in_20virtual_5fvoid_0',['Comparison of &lt;em&gt;erased functionality&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;virtual_void&lt;/span&gt;',['../md_docs_2erased__functionality.html',1,'']]],
  ['erases_20the_20type_20of_20another_20object_20for_20a_20given_20lifetime_20kind_1',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md8',1,'']]],
  ['erasure_20versus_20architectural_20type_20tunnel_2',['&lt;em&gt;Ad hoc&lt;/em&gt; Type Erasure Versus Architectural &lt;em&gt;Type Tunnel&lt;/em&gt;',['../md_docs_2terms__and__definitions.html#autotoc_md28',1,'']]],
  ['eunerased_20type_3',['A &lt;em&gt;typed_any&lt;/em&gt; is a convenience wrapper of an &lt;b&gt;any&lt;/b&gt; for the &lt;b&gt;eunerased&lt;/b&gt; type.',['../md_docs_2terms__and__definitions.html#autotoc_md11',1,'']]],
  ['extension_20members_4',['Extension Members',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['extension_20members_20behaves_20like_20a_20struct_20where_20you_20can_20add_20data_20members_20without_20changing_20the_20definition_20of_20that_20struct_5',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md27',1,'']]],
  ['extension_20method_6',['Extension Method',['../md_docs_2terms__and__definitions.html#autotoc_md23',1,'']]],
  ['extension_20method_20is_20a_20freestanding_20callable_20witch_20acts_20a_20dispatch_5ftable_5ffunction_20on_20the_20first_20paramater_20must_20be_20an_20any_7',['An &lt;b&gt;extension method&lt;/b&gt; is a freestanding callable, witch acts a dispatch_table_function on the first paramater. (must be an &lt;b&gt;any&lt;/b&gt;).',['../md_docs_2terms__and__definitions.html#autotoc_md24',1,'']]],
  ['extension_20method_20to_20solve_20the_20multiple_20dispatch_8',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md25',1,'']]],
  ['extension_20multi_20method_20is_20a_20generalistaion_20of_20the_20extension_20method_20to_20solve_20the_20multiple_20dispatch_9',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md25',1,'']]]
];
