var searchData=
[
  ['c_200x_20concepts_20haskell_20type_20classes_20rust_20traits_20a_20short_20introduction_0',['C++0x Concepts, Haskell type classes, Rust traits, a short introduction',['../subpage1.html',1,'main']]],
  ['c_200x_20concepts_20rust_20traits_20haskell_20type_20classes_1',['Any++, C++0x Concepts, Rust Traits, Haskell Type Classes',['../main.html',1,'']]],
  ['c_2023_20library_20tech_20steve_20downey_2',['Concept Maps using C++23 Library Tech, Steve Downey',['../subpage3.html',1,'main']]],
  ['cast_3',['Cast',['../md_docs_2terms__and__definitions.html#autotoc_md18',1,'Lifetime Cast'],['../md_docs_2terms__and__definitions.html#autotoc_md16',1,'Static Cast vs Dynamic Cast']]],
  ['cast_20vs_20dynamic_20cast_4',['Static Cast vs Dynamic Cast',['../md_docs_2terms__and__definitions.html#autotoc_md16',1,'']]],
  ['castability_5',['Lifetime castability',['../md_docs_2Proxy__overview.html#autotoc_md3',1,'']]],
  ['ci_20matrix_6',['CI Matrix',['../index.html#autotoc_md30',1,'']]],
  ['class_7',['Any++: From Type Erasure to Type Class',['../subpage4.html',1,'main']]],
  ['classes_8',['Any++, C++0x Concepts, Rust Traits, Haskell Type Classes',['../main.html',1,'']]],
  ['classes_9',['Monoid, the &quot;Hello World&quot; of type classes',['../subpage2.html',1,'main']]],
  ['classes_20rust_20traits_20a_20short_20introduction_10',['C++0x Concepts, Haskell type classes, Rust traits, a short introduction',['../subpage1.html',1,'main']]],
  ['clone_20the_20repo_3a_11',['Clone the repo:',['../index.html#autotoc_md28',1,'']]],
  ['clone_5ffrom_12',['clone_from',['../md_docs_2Proxy__overview.html#autotoc_md6',1,'']]],
  ['cmakelists_20txt_3a_13',['Useage in CMakeLists.txt:',['../index.html#autotoc_md27',1,'']]],
  ['code_14',['Description of the Generated Code',['../md_docs_2Traits__inner__working.html#autotoc_md23',1,'']]],
  ['compared_15',['Runtime Performance compared',['../index.html#autotoc_md29',1,'']]],
  ['concept_20maps_20using_20c_2023_20library_20tech_20steve_20downey_16',['Concept Maps using C++23 Library Tech, Steve Downey',['../subpage3.html',1,'main']]],
  ['concepts_20haskell_20type_20classes_20rust_20traits_20a_20short_20introduction_17',['C++0x Concepts, Haskell type classes, Rust traits, a short introduction',['../subpage1.html',1,'main']]],
  ['concepts_20rust_20traits_20haskell_20type_20classes_18',['Any++, C++0x Concepts, Rust Traits, Haskell Type Classes',['../main.html',1,'']]],
  ['conclusions_19',['Further directions and conclusions',['../subpage5.html',1,'main']]],
  ['const_20in_20any_20',['Handling &lt;span class=&quot;tt&quot;&gt;const&lt;/span&gt; in &lt;span class=&quot;tt&quot;&gt;Any++&lt;/span&gt;',['../md_docs_2Constness.html',1,'']]],
  ['context_20of_20any_21',['Terms and Definitions in Context of &lt;span class=&quot;tt&quot;&gt;Any++&lt;/span&gt;',['../md_docs_2terms__and__definitions.html',1,'']]],
  ['crosscast_22',['Crosscast',['../md_docs_2terms__and__definitions.html#autotoc_md19',1,'']]],
  ['crosscast_20factory_20serialization_23',['Showcase 5: &lt;em&gt;Any++&lt;/em&gt; Crosscast + Factory = Serialization',['../index.html#autotoc_md34',1,'']]]
];
