var searchData=
[
  ['data_20members_20without_20changing_20the_20definition_20of_20that_20struct_0',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md27',1,'']]],
  ['definition_20of_20that_20struct_1',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md27',1,'']]],
  ['definitions_20in_20context_20of_20this_20library_2',['Terms and Definitions in Context of This Library',['../md_docs_2terms__and__definitions.html',1,'']]],
  ['derived_20from_20v_5ftable_20with_20no_20additional_20members_20and_20where_20all_20members_20point_20to_20valid_20functions_3',['An object derived from v_table, with no additional members, and where all members point to valid functions.',['../md_docs_2terms__and__definitions.html#autotoc_md5',1,'']]],
  ['describing_20an_20object_20that_20erases_20the_20type_20of_20another_20object_20for_20a_20given_20lifetime_20kind_4',['A concept describing an object that &lt;b&gt;erases&lt;/b&gt; the &lt;b&gt;type&lt;/b&gt; of &lt;b&gt;another&lt;/b&gt; object for a given &lt;em&gt;lifetime&lt;/em&gt; kind.',['../md_docs_2terms__and__definitions.html#autotoc_md8',1,'']]],
  ['description_20of_20the_20generated_20code_5',['Description of the Generated Code',['../md_docs_2Traits__inner__working.html#autotoc_md31',1,'']]],
  ['detailed_20one_6',['A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.',['../md_docs_2terms__and__definitions.html#autotoc_md17',1,'']]],
  ['detailed_20type_20to_20a_20general_20one_7',['An &lt;em&gt;upcast&lt;/em&gt; is a &lt;em&gt;conversion&lt;/em&gt; from a more detailed type to a general one.',['../md_docs_2terms__and__definitions.html#autotoc_md16',1,'']]],
  ['different_20liftime_20within_20certain_20rules_8',['An &lt;b&gt;proxy&lt;/b&gt; can recieve the content of an other &lt;b&gt;proxy&lt;/b&gt; with different &lt;b&gt;liftime&lt;/b&gt; within certain rules.',['../md_docs_2terms__and__definitions.html#autotoc_md19',1,'']]],
  ['dispatch_9',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md25',1,'']]],
  ['dispatch_20matrix_10',['dispatch_table, dispatch_table instance, multi dispatch matrix',['../md_docs_2terms__and__definitions.html#autotoc_md6',1,'']]],
  ['dispatch_5ftable_20dispatch_5ftable_20instance_20multi_20dispatch_20matrix_11',['dispatch_table, dispatch_table instance, multi dispatch matrix',['../md_docs_2terms__and__definitions.html#autotoc_md6',1,'']]],
  ['dispatch_5ftable_20instance_20multi_20dispatch_20matrix_12',['dispatch_table, dispatch_table instance, multi dispatch matrix',['../md_docs_2terms__and__definitions.html#autotoc_md6',1,'']]],
  ['dispatch_5ftable_5ffunction_20on_20the_20first_20paramater_20must_20be_20an_20any_13',['An &lt;b&gt;extension method&lt;/b&gt; is a freestanding callable, witch acts a dispatch_table_function on the first paramater. (must be an &lt;b&gt;any&lt;/b&gt;).',['../md_docs_2terms__and__definitions.html#autotoc_md24',1,'']]],
  ['downcast_14',['&apos;Upcast&apos; vs &apos;Downcast&apos;',['../md_docs_2terms__and__definitions.html#autotoc_md15',1,'']]],
  ['downcast_20is_20a_20conversion_20from_20a_20more_20general_20type_20to_20a_20more_20detailed_20one_15',['A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.',['../md_docs_2terms__and__definitions.html#autotoc_md17',1,'']]],
  ['downcasts_20are_20within_20related_20types_20crosscasts_20are_20between_20unrelated_20types_16',['While &lt;em&gt;up-&lt;/em&gt; and &lt;em&gt;downcasts&lt;/em&gt; are within related types, &lt;em&gt;crosscasts&lt;/em&gt; are between unrelated types.',['../md_docs_2terms__and__definitions.html#autotoc_md22',1,'']]],
  ['dynamic_20cast_17',['Static Cast vs Dynamic Cast',['../md_docs_2terms__and__definitions.html#autotoc_md12',1,'']]],
  ['dynamic_20cast_3a_18',['A &lt;em&gt;dynamic cast&lt;/em&gt;:',['../md_docs_2terms__and__definitions.html#autotoc_md14',1,'']]]
];
