var searchData=
[
  ['matrix_0',['CI Matrix',['../index.html#autotoc_md35',1,'']]],
  ['matrix_1',['dispatch_table, dispatch_table instance, multi dispatch matrix',['../md_docs_2terms__and__definitions.html#autotoc_md7',1,'']]],
  ['members_2',['Extension Members',['../md_docs_2terms__and__definitions.html#autotoc_md27',1,'']]],
  ['members_20and_20where_20all_20members_20point_20to_20valid_20functions_3',['An object derived from v_table, with no additional members, and where all members point to valid functions.',['../md_docs_2terms__and__definitions.html#autotoc_md6',1,'']]],
  ['members_20behaves_20like_20a_20struct_20where_20you_20can_20add_20data_20members_20without_20changing_20the_20definition_20of_20that_20struct_4',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md28',1,'']]],
  ['members_20point_20to_20valid_20functions_5',['An object derived from v_table, with no additional members, and where all members point to valid functions.',['../md_docs_2terms__and__definitions.html#autotoc_md6',1,'']]],
  ['members_20without_20changing_20the_20definition_20of_20that_20struct_6',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md28',1,'']]],
  ['method_7',['Extension Method',['../md_docs_2terms__and__definitions.html#autotoc_md24',1,'']]],
  ['method_20is_20a_20freestanding_20callable_20witch_20acts_20a_20dispatch_5ftable_5ffunction_20on_20the_20first_20paramater_20must_20be_20an_20any_8',['An &lt;b&gt;extension method&lt;/b&gt; is a freestanding callable, witch acts a dispatch_table_function on the first paramater. (must be an &lt;b&gt;any&lt;/b&gt;).',['../md_docs_2terms__and__definitions.html#autotoc_md25',1,'']]],
  ['method_20is_20a_20generalistaion_20of_20the_20extension_20method_20to_20solve_20the_20multiple_20dispatch_9',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['method_20to_20solve_20the_20multiple_20dispatch_10',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['more_20detailed_20one_11',['A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.',['../md_docs_2terms__and__definitions.html#autotoc_md18',1,'']]],
  ['more_20detailed_20type_20to_20a_20general_20one_12',['An &lt;em&gt;upcast&lt;/em&gt; is a &lt;em&gt;conversion&lt;/em&gt; from a more detailed type to a general one.',['../md_docs_2terms__and__definitions.html#autotoc_md17',1,'']]],
  ['more_20general_20type_20to_20a_20more_20detailed_20one_13',['A &lt;em&gt;downcast&lt;/em&gt; is a conversion from a more general type to a more detailed one.',['../md_docs_2terms__and__definitions.html#autotoc_md18',1,'']]],
  ['multi_20dispatch_20matrix_14',['dispatch_table, dispatch_table instance, multi dispatch matrix',['../md_docs_2terms__and__definitions.html#autotoc_md7',1,'']]],
  ['multi_20method_20is_20a_20generalistaion_20of_20the_20extension_20method_20to_20solve_20the_20multiple_20dispatch_15',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['multiple_20dispatch_16',['A &lt;b&gt;extension multi method&lt;/b&gt; is a generalistaion of the &lt;b&gt;extension method&lt;/b&gt;, to solve the &lt;a href=&quot;https://en.wikipedia.org/wiki/Multiple_dispatch&quot;&gt;multiple dispatch&lt;/a&gt; .',['../md_docs_2terms__and__definitions.html#autotoc_md26',1,'']]],
  ['must_20be_20an_20any_17',['An &lt;b&gt;extension method&lt;/b&gt; is a freestanding callable, witch acts a dispatch_table_function on the first paramater. (must be an &lt;b&gt;any&lt;/b&gt;).',['../md_docs_2terms__and__definitions.html#autotoc_md25',1,'']]]
];
