var searchData=
[
  ['ways_20three_20rules_3a_0',['Three ways, three rules:',['../md_docs_2terms__and__definitions.html#autotoc_md20',1,'']]],
  ['where_20all_20members_20point_20to_20valid_20functions_1',['An object derived from v_table, with no additional members, and where all members point to valid functions.',['../md_docs_2terms__and__definitions.html#autotoc_md5',1,'']]],
  ['where_20you_20can_20add_20data_20members_20without_20changing_20the_20definition_20of_20that_20struct_2',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md27',1,'']]],
  ['while_20up_20and_20downcasts_20are_20within_20related_20types_20crosscasts_20are_20between_20unrelated_20types_3',['While &lt;em&gt;up-&lt;/em&gt; and &lt;em&gt;downcasts&lt;/em&gt; are within related types, &lt;em&gt;crosscasts&lt;/em&gt; are between unrelated types.',['../md_docs_2terms__and__definitions.html#autotoc_md22',1,'']]],
  ['witch_20acts_20a_20dispatch_5ftable_5ffunction_20on_20the_20first_20paramater_20must_20be_20an_20any_4',['An &lt;b&gt;extension method&lt;/b&gt; is a freestanding callable, witch acts a dispatch_table_function on the first paramater. (must be an &lt;b&gt;any&lt;/b&gt;).',['../md_docs_2terms__and__definitions.html#autotoc_md24',1,'']]],
  ['with_20an_20proxy_5',['An &lt;em&gt;any&lt;/em&gt; combines a &lt;b&gt;v_table&lt;/b&gt; with an &lt;b&gt;proxy&lt;/b&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md10',1,'']]],
  ['with_20different_20liftime_20within_20certain_20rules_6',['An &lt;b&gt;proxy&lt;/b&gt; can recieve the content of an other &lt;b&gt;proxy&lt;/b&gt; with different &lt;b&gt;liftime&lt;/b&gt; within certain rules.',['../md_docs_2terms__and__definitions.html#autotoc_md19',1,'']]],
  ['with_20no_20additional_20members_20and_20where_20all_20members_20point_20to_20valid_20functions_7',['An object derived from v_table, with no additional members, and where all members point to valid functions.',['../md_docs_2terms__and__definitions.html#autotoc_md5',1,'']]],
  ['within_20certain_20rules_8',['An &lt;b&gt;proxy&lt;/b&gt; can recieve the content of an other &lt;b&gt;proxy&lt;/b&gt; with different &lt;b&gt;liftime&lt;/b&gt; within certain rules.',['../md_docs_2terms__and__definitions.html#autotoc_md19',1,'']]],
  ['within_20related_20types_20crosscasts_20are_20between_20unrelated_20types_9',['While &lt;em&gt;up-&lt;/em&gt; and &lt;em&gt;downcasts&lt;/em&gt; are within related types, &lt;em&gt;crosscasts&lt;/em&gt; are between unrelated types.',['../md_docs_2terms__and__definitions.html#autotoc_md22',1,'']]],
  ['without_20changing_20the_20definition_20of_20that_20struct_10',['An &lt;b&gt;extension members&lt;/b&gt; behaves like a &lt;em&gt;struct&lt;/em&gt;, where you can add data members without changing the definition of that &lt;em&gt;struct&lt;/em&gt;.',['../md_docs_2terms__and__definitions.html#autotoc_md27',1,'']]],
  ['working_20of_20traits_20in_20any_11',['The Inner Working Of &lt;span class=&quot;tt&quot;&gt;Traits&lt;/span&gt; In &lt;span class=&quot;tt&quot;&gt;Any++&lt;/span&gt;',['../md_docs_2Traits__inner__working.html',1,'']]],
  ['wrapper_20of_20an_20any_20for_20the_20eunerased_20type_12',['A &lt;em&gt;typed_any&lt;/em&gt; is a convenience wrapper of an &lt;b&gt;any&lt;/b&gt; for the &lt;b&gt;eunerased&lt;/b&gt; type.',['../md_docs_2terms__and__definitions.html#autotoc_md11',1,'']]]
];
