#include "class_hierarchy_test_hierarchy.hpp"

VV_RUNTIME_INSTANCE(TestDomain::A1)
VV_RUNTIME_INSTANCE(TestDomain::A2)
VV_RUNTIME_INSTANCE(TestDomain::B1)
VV_RUNTIME_INSTANCE(TestDomain::B2)
VV_RUNTIME_INSTANCE(TestDomain::B3)
VV_RUNTIME_INSTANCE(TestDomain::C1)
VV_RUNTIME_INSTANCE(TestDomain::C2)
VV_RUNTIME_INSTANCE(TestDomain::C3)
VV_RUNTIME_INSTANCE(TestDomain::C)
VV_RUNTIME_INSTANCE(TestDomain::D)
