#pragma once

#include "class_hierarchy/class_hierarchy.h"
#include "erased/interface/interface.h"
#include "erased/lifetime/observer.h"
#include "erased/lifetime/shared_const.h"
#include "erased/lifetime/unique.h"
#include "erased/lifetime/value.h"
#include "error.h"
#include "m_table/lifetime.h"
#include "m_table/open_method.h"
#include "open_method/algorithm.h"
#include "open_method/table.h"
#include "typeid/factory.h"
#include "typeid/open_method.h"
#include "typeid_cast/cast.h"
